---
variables:
  GIT_SUBMODULE_STRATEGY: recursive

#image: gcc:13.2
before_script:
  # - apt-get update --yes
  # - apt-get install --yes cmake clang-tidy ninja-build curl zip unzip tar
  # - rm -rf build
  # - mkdir build
  - git submodule sync --recursive
  - git submodule update --init
  - ./vendor/vcpkg/bootstrap-vcpkg.sh
  - cmake --preset=debug -B build/

stages:
  - build
  - lint

build:
  stage: build
  script:
    - cmake --build build/

clang-tidy:
  stage: lint
  script:
    - find src/ -name \*.cpp -print0 | xargs -0 -n 1 clang-tidy -p build/