---
variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: gcc:13.2
before_script:
  - apt-get update --yes
  - apt-get install --yes cmake clang-tidy ninja-build curl zip unzip tar
  - rm -rf build
  - mkdir build
  - git submodule update --init --recursive
  - ./vendor/vcpkg/bootstrap-vcpkg.sh

stages:
  - build
  - lint

build:
  stage: build
  script:
    - cmake -B build/ -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build/

clang-tidy:
  stage: lint
  script:
    - find src/ -name \*.cpp -print0 | xargs -0 -n 1 clang-tidy -p build/